/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6PauTxu8aU8
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { GoalIcon, RocketIcon, RouteIcon } from "lucide-react";
import Image from "next/image";

export function ChainGiving() {
  return (
    <section className="w-full">
      <header className="flex items-center justify-between px-6 py-4">
        <Link className="flex items-center space-x-2" href="#">
          <HeartIcon className="h-6 w-6 text-red-600" />
          <span className="text-lg font-semibold">Chain.Giving</span>
        </Link>
        <nav className="space-x-4">
          <Link className="text-sm font-medium" href="#">
            Home
          </Link>
          <Link className="text-sm font-medium" href="#">
            About
          </Link>
          <Link className="text-sm font-medium" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="px-6 py-12 text-center">
        <h1 className="text-3xl font-bold">Chain.Giving</h1>
        <p className="max-w-lg mx-auto mt-4 text-gray-600">
          Leveraging Polkadot for fundraising and aid distribution
        </p>
        <p>
          <a href="https://discord.gg/d3QnfrebmY">
            <Button className="mt-6 px-8 py-3 bg-green-500 text-white rounded">
              Join us on Discord{" "}
            </Button>
          </a>
          <a href="https://forum.polkadot.network/t/chain-giving-leveraging-the-polkadot-network-for-fundraising-and-aid-distribution/5371">
            <Button className="mt-5 px-8 py-3 bg-blue-600 text-white rounded-md">
              Learn More
            </Button>
          </a>
        </p>
      </main>
      <section className="px-6 py-12 bg-gray-100">
        <h2 className="text-2xl font-bold mb-4">Our Mission</h2>
        <p className="max-w-lg mx-auto mb-6 text-gray-600">
          We strive to bring transparency and efficiency to charitable giving.
        </p>
        {/*<img*/}
        {/*    alt="Our mission"*/}
        {/*    className="mx-auto rounded"*/}
        {/*    height="400"*/}
        {/*    src="/placeholder.svg"*/}
        {/*    style={{*/}
        {/*      aspectRatio: "600/400",*/}
        {/*      objectFit: "cover",*/}
        {/*    }}*/}
        {/*    width="600"*/}
        {/*/>*/}
        <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
          <div className="flex flex-col items-center">
            <RouteIcon className="w-10 h-10 mb-4" />
            <b>End to End Transparency</b>
            <p className="text-center">
              Covers the full journey from fundraising to carrying out aid
              programs.
            </p>
          </div>
          <div className="flex flex-col items-center">
            <GoalIcon className="w-10 h-10 mb-4" />
            <b>Trustless</b>
            <p className="text-center">
              Users don&#39;t have to trust a single party to ensure donations
              will reach their targets.
            </p>
          </div>
          <div className="flex flex-col items-center">
            <RocketIcon className="w-10 h-10 mb-4" />
            <b>Fast</b>
            <p className="text-center">
              On-chain transactions guarantee instant settlement of payments
            </p>
          </div>
        </div>
      </section>
      <section className="px-6 py-12">
        <h2 className="text-2xl font-bold mb-4">Our Tech Stack</h2>
        <p className="max-w-lg mx-auto mb-6 text-gray-600">
          Chain.Giving is made possible thanks to those technologies
        </p>
        <div className="flex justify-around">
          <a href="https://substrate.io/">
            <Card>
              <CardHeader>
                <Image
                  alt="Substrate"
                  className="mx-auto rounded-full"
                  height="150"
                  src="/images/paritysubstrate.svg"
                  style={{
                    aspectRatio: "150/150",
                  }}
                  width="150"
                />
                <h3 className="text-lg font-semibold mt-2 text-center">
                  Made with Substrate
                </h3>
              </CardHeader>
              <CardContent>
                <p className="text-center text-gray-600">
                  The industry leading blockchain framework
                </p>
              </CardContent>
            </Card>
          </a>
          <a href="https://polkadot.network/">
            <Card>
              <CardHeader>
                <Image
                  alt="Team Member 1"
                  className="mx-auto rounded-full"
                  height="150"
                  src="/images/Polkadot_Token_Pink.svg"
                  style={{
                    aspectRatio: "150/150",
                  }}
                  width="150"
                />
                <h3 className="text-lg font-semibold mt-2 text-center">
                  Candidate to join Polkadot
                </h3>
              </CardHeader>
              <CardContent>
                <p className="text-center text-gray-600">
                  We plan to become a full fledged Parachain of the Polkadot
                  network
                </p>
              </CardContent>
            </Card>
          </a>
        </div>
      </section>
      <footer className="flex items-center justify-between px-6 py-4 bg-gray-800 text-white">
        <div className="flex items-center space-x-2">
          <Link href="https://twitter.com/chain_giving">
            <TwitterIcon className="h-6 w-6" />
          </Link>
          <Link href="https://github.com/chaingiving">
            <GithubIcon className="h-6 w-6" />
          </Link>
          <Link href="https://discord.gg/d3QnfrebmY">
            <DiscordIcon className="h-6 w-6" />
          </Link>
        </div>
        <p className="text-sm">© Chain.Giving. All rights reserved.</p>
      </footer>
    </section>
  );
}

function HeartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  );
}

function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function DiscordIcon(props: any) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      viewBox="0 0 127.14 96.36"
      width="24"
      height="24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path
        fill="#fff"
        d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.79,32.65-1.71,56.6.54,80.21h0A105.73,105.73,0,0,0,32.71,96.36,77.7,77.7,0,0,0,39.6,85.25a68.42,68.42,0,0,1-10.85-5.18c.91-.66,1.8-1.34,2.66-2a75.57,75.57,0,0,0,64.32,0c.87.71,1.76,1.39,2.66,2a68.68,68.68,0,0,1-10.87,5.19,77,77,0,0,0,6.89,11.1A105.25,105.25,0,0,0,126.6,80.22h0C129.24,52.84,122.09,29.11,107.7,8.07ZM42.45,65.69C36.18,65.69,31,60,31,53s5-12.74,11.43-12.74S54,46,53.89,53,48.84,65.69,42.45,65.69Zm42.24,0C78.41,65.69,73.25,60,73.25,53s5-12.74,11.44-12.74S96.23,46,96.12,53,91.08,65.69,84.69,65.69Z"
      />
    </svg>
  );
}
